version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2022.09
    environment:
      FOO: bar
    parallelism: 3
    resource_class: small
    working_directory: ~/my-app
    steps:
       - run : echo "Building the app"
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Run tests
          command: python tests.py

      - store_test_results:
          path: test-results
  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - run: echo "Deploying to production server"

workflows:
  build_and_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build 