version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    resource_class: small
    steps:
      - checkout
      - run: python main.py
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Run tests
          command: python tests.py &&  mkdir -p test-results &&             python -m unittest discover -s tests -p "*.py" > test-results/results.log || true
            python -m unittest discover -s tests -p "*.py" > test-results/results.log || true

      - store_test_results:
          path: test-results
  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - run: echo "Deploying to production server"

workflows:
  build_and_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build 